### ISSUE TITLE
Android Basics: create-dice-roller-app-with-button

### ISSUE THREAD

**Issue by Petenmr** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#10]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-create-dice-roller-app-with-button?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-create-dice-roller-app-with-button#3

**In which task and step of the codelab can this issue be found?**
Enable auto imports
1  In Windows go to File > Other Setting > Setting for New Projects... .

**Describe the problem**
Path failure:
In my case path:
File > Settings > Editor > General > Auto Import

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ Android Studio\bin\studio64.exe" download latest 4 days ago.
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@Petenmr 
Thank you for reaching out to us.
What is your operating system. Are you on Windows or macOS?

**Comment by Petenmr** [comment]
Win10 Home 2019 64bit
Intel i3-4160 @3.60 GHz
Mem 12GB


Op ma 1 mrt. 2021 23:00 schreef jtavva <notifications@github.com>:

**Comment by osuleymanova** [comment]
@Petenmr 
Thank you for reaching out to us. The issue is fixed and will be published soon.
