### ISSUE TITLE
Android Basics: create-dice-roller-app-with-button

### ISSUE THREAD

**Issue by Lunarclipper** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#102]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-create-dice-roller-app-with-button?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-create-dice-roller-app-with-button#4

**In which task and step of the codelab can this issue be found?**
Task 5, Step 1

**Describe the problem**
The sentence "The code saves a reference to the Button object in a variable called rollButton, not the Button object itself." is printed twice. In the included screenshot you will see the first instance of the sentence highlighted in orange. The second instance is between the light blue text boxes.
![duplicate_line_2022-01-26_03-43-02](https://user-images.githubusercontent.com/94221018/151149564-42074b70-380d-4fe5-a0cf-2bea7508acfd.png)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@Lunarclipper 
Thank you for reaching out to us and reporting this issue. The typo is fixed and will be published soon.
![Screen Shot 2022-04-11 at 3 29 19 PM](https://user-images.githubusercontent.com/86437155/162843789-0a1daab3-6fb4-4399-878d-b65c2c78c845.png)
