### ISSUE TITLE
Android Basics: conditional-dice-roll-behavior

### ISSUE THREAD

**Issue by viperguynaz** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#105]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-conditional-dice-roll-behavior

**In which task and step of the codelab can this issue be found?**
Add conditional behavior in Kotlin

**Describe the problem**
This codelab describes using `fun main` but the code should be in `MainActivity` -> `fun onCreate`

**Comment by osuleymanova** [comment]
@viperguynaz 
Thank you for reaching out to us. In this codelab we require to use a Kotlin program that uses variables, functions with arguments, classes with methods, and prints a result to the console: https://developer.android.com/training/kotlinplayground
