### ISSUE TITLE
Android Basics: create-dice-roller-app-with-button

### ISSUE THREAD

**Issue by AthulMuralidhar** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#11]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-create-dice-roller-app-with-button?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-create-dice-roller-app-with-button#5

**In which task and step of the codelab can this issue be found?**
step: 6

**Describe the problem**
There is not really a bug here, but an update on the new Andriod studio. The "change to private" function does not really exist now, so it would be better to just type the `private` word out for the `val numSides` variable

**Versions**
_Android Studio version:_  
Android Studio 4.1.2
Build #AI-201.8743.12.41.7042882, built on December 20, 2020
Runtime version: 1.8.0_242-release-1644-b3-6915495 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Registry: ide.new.welcome.screen.force=true, external.system.auto.import.disabled=true
Non-Bundled Plugins: org.jetbrains.kotlin

_API version of the emulator:_  30

**Comment by osuleymanova** [comment]
@AthulMuralidhar 
Thank you for reaching out to us. The issue is fixed and will be published soon.
