### ISSUE TITLE
Android Basics: create-dice-roller-app-with-button

### ISSUE THREAD

**Issue by jderijke** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#112]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**
4: Introduction to activities

**Describe the problem**
Location of auto import has moved in bumblebee

**Comment by osuleymanova** [comment]
@jderijke 
Thank you for reaching out to us. The location and image are updated and will be published soon.
