### ISSUE TITLE
Android Basics: create-dice-roller-app-with-button

### ISSUE THREAD

**Issue by csaltos** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#115]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-create-dice-roller-app-with-button?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-create-dice-roller-app-with-button#3

**In which task and step of the codelab can this issue be found?**
4

**Describe the problem**
Just a minor missing update, on new Android Studio versions de auto import is under Editor and not at Other Settings

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@csaltos 
Thank you for reaching out to us. In the latest Android Studio Bumblebee version the path for Auto Import is under Other Settings:
![Screen Shot 2022-04-11 at 3 08 41 PM](https://user-images.githubusercontent.com/86437155/162845392-ec98a804-5a9a-47c3-be54-d0e744ba8b9b.png)
