### ISSUE TITLE
Android Basics: create-dice-roller-app-with-button - suggestion

### ISSUE THREAD

**Issue by AthulMuralidhar** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#12]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-create-dice-roller-app-with-button?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-create-dice-roller-app-with-button#5

**In which task and step of the codelab can this issue be found?**
step 6: 

**Describe the suggestion**

- It is great that you are introducing scoping here, but is it really necessary for the code to work in this case?  I was able to compile and run without using the public / private scoping

- I am providing this input here so that the new aspiring Android / kotlin developers dont get bogged down by the details of scoping and can get their apps out fast (and with less compile time errors)

- Thanks again for the developer resources, they are super useful ❤️

**Comment by jtavva** [comment]
@AthulMuralidhar 
Thank you for reaching out to us.
It is good coding practice to specify the scope. If no scope is specified, default scope will be used.
