### ISSUE TITLE
Android Basics: create-dice-roller-in-kotlin

### ISSUE THREAD

**Issue by hbkysf27** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#121]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-create-dice-roller-in-kotlin?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-create-dice-roller-in-kotlin#5

**In which task and step of the codelab can this issue be found?**

[Classes and object instances in Kotlin]  - Customize Your Dice (Step 06 )(https://developer.android.com/codelabs/basic-android-kotlin-training-create-dice-roller-in-kotlin?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-create-dice-roller-in-kotlin)

**Describe the problem**
val cannot be reassigned
```
`class Dice(val numSides:Int)
{
        fun roll():Int
    {
        val randomNumber=(1..numSides).random()
        return randomNumber
    }
}`
```

this is the code that was given in the codelabs that shows val cannot be reassigned
```
fun main() {
    val myFirstDice = Dice(6)
    val diceRoll = myFirstDice.roll()
    println("Your ${myFirstDice.numSides} sided dice rolled ${diceRoll}!")
    
    val mySecondDice = Dice(20)
    println("Your ${mySecondDice.numSides} sided dice rolled ${mySecondDice.roll()}!")
}

class Dice (val numSides: Int) {

    fun roll(): Int {
        val randomNumber = (1..numSides).random()
        return randomNumber
    }
}
```
this is my code which works
```
fun main()
{
    val myFirstDice=Dice(6)  
    val diceRoll=myFirstDice.roll()
    println("Your ${myFirstDice.numSides} sided dice rolled ${diceRoll} !!!!!")
    myFirstDice.numSides=20
     println("Your ${myFirstDice.numSides} sided dice rolled ${myFirstDice.roll()} !!!!!")
    
}
class Dice(var numSides:Int)
{
        fun roll():Int
    {
        val randomNumber=(1..numSides).random()
        return randomNumber
    }
}
```

**Steps to reproduce?**
1. Go to... [https://developer.android.com/codelabs/basic-android-kotlin-training-create-dice-roller-in-kotlin?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-create-dice-roller-in-kotlin](url)
2. Click on... customize your dice in the dashboard panel or scroll down to the 6th heading Customize your dice run the 10th option which is the final code and check
3. See error...

**Versions**
_Android Studio version:_  ---
_API version of the emulator:_  Running on kotlin v. 1.6.20

**Additional information**

the below image should be the correct code i guess because when i run the code using the val variable, it showed as val cannot be reassigned

![image](https://user-images.githubusercontent.com/86113227/163710571-bca8d250-e767-47d5-be16-f56eb7ae6d2b.png)

![image](https://user-images.githubusercontent.com/86113227/163710500-e68d581b-7636-4ede-b557-cec596f72cb4.png)

![image](https://user-images.githubusercontent.com/86113227/163710443-fa8b565b-3b33-45f6-9658-9200ee68fc42.png)

**Comment by osuleymanova** [comment]
@hbkysf27 
Thank you for reaching out to us and providing the screenshots. The issue won't be fixed as it's not reproducible. The code provided in the codelab's code snippet is correct.
