### ISSUE TITLE
Android Basics: conditional-dice-roll-behavior

### ISSUE THREAD

**Issue by Matthaeus07** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#123]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-conditional-dice-roll-behavior

**In which task and step of the codelab can this issue be found?**

On page 2 ("2. Decision making within your code") the last code box at the bottom.

**Describe the problem**

The text in the code box should display an output.
However this output is displayed in different colors like code would be.

**Screenshot**

![image](https://user-images.githubusercontent.com/87285710/168444233-1bcf3ced-5e43-4638-a2c8-5314cb3b0d6b.png)

**Comment by osuleymanova** [comment]
@Matthaeus07 
Thank you for reaching out to us. The issue is fixed and will be published soon:
<img width="855" alt="Screen Shot 2022-05-23 at 5 33 02 PM" src="https://user-images.githubusercontent.com/86437155/169925370-588252e1-24c5-4bde-b643-17b1a4f42287.png">
