### ISSUE TITLE
Android Basics: create-dice-roller-app-with-button

### ISSUE THREAD

**Issue by oliver11111** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#13]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-create-dice-roller-app-with-button?authuser=2&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%3Fauthuser%3D2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-create-dice-roller-app-with-button#6

**In which task and step of the codelab can this issue be found?**
Comment your code

**Describe the problem**
The documentation states, "Use the /** and **/ symbols at the beginning and end of your comment", but the example uses "*/" at the end of the comment.

**Comment by jtavva** [comment]
@oschubert 
Thank you for reaching out to us.
Could please tell us which task are you referring to? 
Also please add screenshots and reference links of the documentation.

**Comment by osuleymanova** [comment]
@oliver11111 
Thank you for reaching out to us. The typo is fixed and will be published soon. Comments should start with /** and end  */.
