### ISSUE TITLE
Android Basics: conditional-dice-roll-behavior

### ISSUE THREAD

**Issue by Somentus** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#131]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

2. Decision making within your code => Use an else if combination to add alternative conditions

**Describe the problem**

![image](https://user-images.githubusercontent.com/15087153/174764846-3d3ae660-94b2-4eaf-87bb-a7640586a0e8.png)
This text output is being formatted as if it's code, rather than being shown as plaintext.

**Steps to reproduce?**
1. Go to...
2. Click on...
4. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @Somentus 

Thank you for pointing out this issue.

I will share with the team to see if they can correct this.

Hope you are enjoying the course!

Regards.
