### ISSUE TITLE
Issue with R.id.button

### ISSUE THREAD

**Issue by WanderingSam** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#137]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-create-dice-roller-app-with-button?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-create-dice-roller-app-with-button#4

**In which task and step of the codelab can this issue be found?**
Page 5, when the you run the code 
**Describe the problem**
the button part of R.id.button is flagged as an error.  It won't let me run the code unless the error is resolved
Screenshot:
![sc](https://user-images.githubusercontent.com/49308046/179053591-4e00b420-2b43-45b4-a21b-983dff3bd68d.png)

**Comment by aled-lewis** [comment]
Hello there,

I know this is an old thread, but I noticed it while logging an issue of my own and thought I'd leave this in case anyone comes across it in future.

I had this same error. I found that on Task 2 of this lesson, the template you are told to use is incorrect. I had this issue when I followed the instruction and created a new project with the 'Empty Activity' template. However if I create the new project with 'Empty Views Activity' template, the button part of it works.
