### ISSUE TITLE
Privacy Policy – Privacy & Terms – Google

### ISSUE THREAD

**Issue by Bitcoin3Og** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#147]
https://policies.google.com/privacy?hl=en

**Comment by Bitcoin3Og** [comment]
https://pbs.twimg.com/profile_images/1532247494486261760/j3TSkjkU.png

**Comment by johnshea** [comment]
Hi.

Please leave additional details regarding the course so we can help you.

Regards.
