### ISSUE TITLE
https://github.com/google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution/issues/148

### ISSUE THREAD

**Issue by Bitcoin3Og** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#149]
https://github.com/github/docs/blob/main/content/get-started/learning-about-github/githubs-products.md#L8

**Comment by johnshea** [comment]
Hi.

Please leave additional details regarding the course so we can help you.

Regards.
