### ISSUE TITLE
Android Basics: conditional-dice-roll-behavior

### ISSUE THREAD

**Issue by Sam-sk** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#151]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
Se o Brasileiro ganha um salario minimo, e vive sempre no comodismo, qual a chance dele se tornar um miliorário?

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @Sam-sk 

It was not clear from your comments what part of the course that you were having an issue.

Please re-open your issue with the URL of the codelab and steps to reproduce it so we can help you.

Regards.
