### ISSUE TITLE
Android Basics: create-dice-roller-app-with-button

### ISSUE THREAD

**Issue by jayisreallycool** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#16]
**https://github.com/google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution**

**Solution Code Url**

**Solution Code Will Not Compile on my Android galaxy s8 **

**Steps to reproduce?**
1. https://github.com/google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution...
2. compile...
3. something is really wrong here or not easily explained im stuck on this guide... app crashes when I press button
4. I am able to get the Dice Rolled on Clicklistener

**19 kit kat**
_Android Studio version:_  4.1.3
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@jayisreallycool 
Thank you for reaching out to us. 
Please follow the steps described in the codelab, or verify your code with the solution code provided in the codelab. If it doesn't help please feel free to reopen the issue with more details and logs.
