### ISSUE TITLE
Android Basics: create-dice-roller-app-with-button

### ISSUE THREAD

**Issue by ooopsididitagain** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#18]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-create-dice-roller-app-with-button?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-create-dice-roller-app-with-button#3

**In which task and step of the codelab can this issue be found?**

4. Introduction to Activities

**Describe the problem**
Enable auto imports, paragraph 1. 
In Android Studio, open the settings by going to File > New Project Settings > Preferences for New Projects on macOS. In Windows go to File > **Other Setting** > Setting for New Projects... .

Need to change **Other Setting** to **New Project Settings**.

**Steps to reproduce?**
1. Go to link from URL of codelab
2. Go to Introduction to Activities, Enable auto imports, paragraph 1. 
3. See error on windows preferens description.

**Versions**
Android Studio 4.1.3

**Additional information**

![image](https://user-images.githubusercontent.com/46779286/115528515-c6dd7e80-a29a-11eb-938e-a04c650f7f80.png)
![image](https://user-images.githubusercontent.com/46779286/115528558-d2c94080-a29a-11eb-8a5b-3e6773f9915a.png)

**Comment by osuleymanova** [comment]
@ooopsididitagain 
Thank you for reaching out to us. You are right, the correct path in Windows is File > Settings > Editor > General > Auto Import. The issue is fixed and will be published soon.
