### ISSUE TITLE
Android Basics: create-dice-roller-app-with-button[Auto Import setting position moved]

### ISSUE THREAD

**Issue by Jason96170** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#19]
**URL of codelab**
[Create an interactive Dice Roller app](https://developer.android.com/codelabs/basic-android-kotlin-training-create-dice-roller-app-with-button?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-create-dice-roller-app-with-button#3)

**In which task and step of the codelab can this issue be found?**
Add a button to an app > Create an interactive Dice Roller app > Enable auto imports

**Describe the problem**
The Auto Import setting position has been moved from `Other Settings > Auto Import` to `Editor > General > Auto Import`.
![image](https://user-images.githubusercontent.com/72907787/116775180-2eae7900-aa94-11eb-979c-bb880330f303.png)

**Versions**
_Android Studio version:_ 4.1.3

**Comment by osuleymanova** [comment]
@Jason96170 
Thank you for reaching out to us. You are right, the correct path in Windows is File > Settings > Editor > General > Auto Import. The issue is fixed and will be published soon.

**Comment by osuleymanova** [comment]
Duplicate of #18
