### ISSUE TITLE
Android Basics: create-dice-roller-app-with-button

### ISSUE THREAD

**Issue by Cathie1953** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#2]
**URL of codelab**https://developer.android.com/codelabs/basic-android-kotlin-training-create-dice-roller-app-with-button?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-create-dice-roller-app-with-button#7

**In which task and step of the codelab can this issue be found?**  In the solution downloaded from github

**Describe the problem**  There is no Toast in the solution; my written code didn't work, so I just downloaded the solution and there is no Toast action as described at URL: https://developer.android.com/codelabs/basic-android-kotlin-training-create-dice-roller-app-with-button?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-create-dice-roller-app-with-button#4

I am completely inexperienced, so it has been hours trying to figure out what I did wrong.  It looks like it is possible it wasn't me this time.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error... 
**Versions**
_Android Studio version:_ 4.1.1
_API version of the emulator:_ 30x86?

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
I changed the code as follows and it worked:
 // Set a click listener on the button to roll the dice when the user taps the button
        rollButton.setOnClickListener {
            rollDice()
            val toast = Toast.makeText(this, "Dice Rolled!", Toast.LENGTH_SHORT)
            toast.show()
        }

**Comment by jtavva** [comment]
@Cathie1953 
Thank you for reaching out to us.
Yes, the solution code does't include the toast message, we replace the toast message with `rollDice()` code at the end of the codelab.

in the [Create an interactive Dice Roller app](https://developer.android.com/codelabs/basic-android-kotlin-training-create-dice-roller-app-with-button?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-create-dice-roller-app-with-button#4) codelab, in task **5. Make the Button interactive** you can refer to the code where we add the toast. 

```
val rollButton: Button = findViewById(R.id.button)
       rollButton.setOnClickListener {
           val toast = Toast.makeText(this, "Dice Rolled!", Toast.LENGTH_SHORT)
           toast.show()
       }
```

**Comment by Cathie1953** [comment]
Thanks for drawing my attention to my mistake...I will get it eventually!  I just didn't scroll to the end of the page of instructions, I thought I was done when it worked...thanks again.
