### ISSUE TITLE
Typo found!

### ISSUE THREAD

**Issue by riyasvmc** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#22]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-create-dice-roller-app-with-button?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-create-dice-roller-app-with-button#6

**In which task and step of the codelab can this issue be found?**
Inside 'Create an interactive Dice Roller app' > 7th step > Comment your code

**Describe the problem**
Typo found as this '/** and **/', this is a commend symbol, but the correct way is '/** and */'.
One star at the end required.

**Comment by osuleymanova** [comment]
@riyasvmc 
Thank you for reaching out to us. The issue is fixed and will be published soon. Comments should start with /** and end  */.
