### ISSUE TITLE
Android Basics: create-dice-roller-app-with-button

### ISSUE THREAD

**Issue by KKH-tw** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#24]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-create-dice-roller-app-with-button#2

**In which task and step of the codelab can this issue be found?**
In the "Style the TextView" section.

**Describe the problem**
The following sentence is put in the code block, but it seems more appropriate to be in plain text:
"Note that because this text is only viewed by app developers, you don't need to make a string resource for it."

**Steps to reproduce?**
As stated above

**Versions**
Not applicable.

**Additional information**
Nil.

**Comment by osuleymanova** [comment]
@KKH-tw 
Thank you for reaching out to us. The issue is fixed and will be published soon.
