### ISSUE TITLE
Android Basics: create-dice-roller-app-with-button

### ISSUE THREAD

**Issue by hsieh-sunghai** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#25]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-create-dice-roller-app-with-button?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-create-dice-roller-app-with-button#3

**In which task and step of the codelab can this issue be found?**
Incorrect content

**Describe the problem**
There is no "File > New Project Settings > Preferences for New Projects" on MacOS

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@hsieh-sunghai 
Thank you for reaching out to us. The path provided in the codelab "on macOS, open the settings by going to File > New Project Settings > Preferences for New Projects..." is absolutely correct. Please check the steps in the screenshot below and follow them in your Android Studio. Hope it helps!
![Screen Shot 2021-11-30 at 5 01 04 PM](https://user-images.githubusercontent.com/86437155/144152886-d55d99b6-69cb-4b96-b119-4b844e76411a.png)
