### ISSUE TITLE
Android Basics: create-dice-roller-app-with-button

### ISSUE THREAD

**Issue by andrewsawesome** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#26]
[](https://developer.android.com/codelabs/basic-android-kotlin-training-create-dice-roller-app-with-button?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-create-dice-roller-app-with-button#5)

Create an interactive Dice Roller Part 6

In step 3, the code is written val diceRoll = dice.roll(), and this is repeated at the end of step 5. The code should instead be val diceRoll = Dice.roll(), otherwise the Gradle build will fail

**Steps to reproduce?**
1. Follow the guide Create an interactive Dice Roller up to part 6.
2. Click on dice in the code val diceRoll = dice.roll()
3. You will see an error on the line, with the suggestion to create a local variable, parameter, or property 'dice'. When trying to run the app, the gradle build will fail with the error Unresolved reference: dice: 22

**Versions**
_Android Studio version: 4.2.1
_API version of the emulator:30

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@andrewsawesome 
Thank you for reaching out to us. The code provided in the codelab is correct. Following the steps in the codelab there should be no error. We appreciate if you provide the screenshots of your code and the error message so we could advise accordingly.
