### ISSUE TITLE
Android Basics: create-dice-roller-app-with-button

### ISSUE THREAD

**Issue by luisamilcarr** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#28]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

val rollButton: Button = findViewById(R.id.button) //switched to
val rollButton = findViewById<Button>(R.id.button)

val resultTextView: TextView = findViewById(R.id.textView) //switched to
val resultTextView = findViewById<TextView>(R.id.textView)

**Comment by osuleymanova** [comment]
@luisamilcarr 
Thank you for reaching out to us and suggesting your code variant. We stand with the code provided in the codelab is correct, so no further actions needed.
