### ISSUE TITLE
Android Basics: create-dice-roller-app-with-button

### ISSUE THREAD

**Issue by spardax212** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#29]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**
add the dice roll logic.
**Describe the problem**
when adding the private fun rollDice information the val dice = Dice(6) has an issue
the Dice is showing red and i'm unsure of what to do to make the application run.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ latest
_API version of the emulator:_ 19.1 kit kat

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

![codingissue](https://user-images.githubusercontent.com/85908362/121967604-898aef80-cd25-11eb-9dff-ee2b8f0ef6d7.jpeg)

**Comment by hassanbob** [comment]
you miss 
(numSides)

**Comment by osuleymanova** [comment]
@spardax212 
Thank you for reaching out to us. 
So it looks like  in your code val numSides is not private:
class Dice(private val numSides: Int) {

And I don't see import androidx.appcompat.app.AppCompatActivity
Please try to make edits in your code or verify with the solution code below:
package com.example.diceroller

import android.os.Bundle
import android.widget.Button
import android.widget.TextView
import androidx.appcompat.app.AppCompatActivity

class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val rollButton: Button = findViewById(R.id.button)
        rollButton.setOnClickListener { rollDice() }
    }

    private fun rollDice() {
        val dice = Dice(numSides:6)
        val diceRoll = dice.roll()
        val resultTextView: TextView = findViewById(R.id.textView)
        resultTextView.text = diceRoll.toString()
    }
}

class Dice(private val numSides: Int) {
    fun roll(): Int {
        return (1..numSides).random()
    }
}

Happy coding!
