### ISSUE TITLE
Android Basics: create-dice-roller-app-with-button

### ISSUE THREAD

**Issue by ahmedbabar91** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#30]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-create-dice-roller-app-with-button?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-create-dice-roller-app-with-button#3

**In which task and step of the codelab can this issue be found?**
Enable auto imports

**Describe the problem**
The windows path to enable auto import is shown as File > Other Setting > Setting for New Projects... . This is incorrect

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@ahmedbabar91 
Thank you for reaching out to us. 
In the codelab there are 2 paths described: for Windows and macOS users. Please select the path accordingly. 
As for Windows it should be File > Settings > Editor > General > Auto Import.
