### ISSUE TITLE
Android Basics: create-dice-roller-app-with-button

### ISSUE THREAD

**Issue by VanessaRoldan** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#34]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-create-dice-roller-app-with-button?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-create-dice-roller-app-with-button#5

**In which task and step of the codelab can this issue be found?**
6 Add the dice roll logic
2 Notice that Android Studio may underline numSides with a wavy gray line. (This may take a moment to appear.)
5 Convert diceRoll to a string and use that to update the text of the resultTextView.

**Describe the problem**
No gray line under numSides (Studio Android), I cannot put it in private. 
Studio Android doesnt recognize "Dice" as a reference. 
**Steps to reproduce?**
1. Go to... 
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ Yes
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

![image](https://user-images.githubusercontent.com/87163513/125023470-aeb80880-e01a-11eb-85de-0d5a239563c9.png)

![image](https://user-images.githubusercontent.com/87163513/125023489-b677ad00-e01a-11eb-93c2-1e3345ccae23.png)

**Comment by osuleymanova** [comment]
@VanessaRoldan 
Thank you for reaching out to us and providing the screenshot of your code. 
It looks like in your code 1 step is missing:
![Screen Shot 2022-04-11 at 2 45 01 PM](https://user-images.githubusercontent.com/86437155/162838973-7e553b93-8092-401c-9b86-fb96563dcdec.png)
The code should look like the below:
![Screen Shot 2022-04-11 at 2 50 17 PM](https://user-images.githubusercontent.com/86437155/162839381-8cdf0ba2-1803-4fad-83c5-fe5a7764cbca.png)
Hope it helps! Please update your code and if you face the error message again, feel free to reopen the ticket.
 Happy coding!
