### ISSUE TITLE
Android Basics: conditional-dice-roll-behavior

### ISSUE THREAD

**Issue by shalombentenzingnamchyo** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#35]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-conditional-dice-roll-behavior?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-conditional-dice-roll-behavior#5

**In which task and step of the codelab can this issue be found?**
In "Add conditional behavior in Kotlin" please correct this.
`matches-value -&gt;` *`execute-this-code`*

`matches-value -&gt;` *`execute-this-code`*

**Describe the problem**
only a small problem that -&gt must be greater than right?
(not a big issue; Hope you forgive if i am disturbing)

Thank you

**Comment by osuleymanova** [comment]
@shalombentenzingnamchyo 
Thank you for reaching out to us. The issue is fixed and will be published soon:
when (variable) {
    matches-value -> execute-this-code
    matches-value -> execute-this-code
    …
}
