### ISSUE TITLE
Android Basics: conditional-dice-roll-behavior

### ISSUE THREAD

**Issue by TechSlugz** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#40]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

&gt used to show a > but it doesn't show > just &gt. I am using google dev browser and haven't checked in other browsers.
It is in the summery when showing how a when statement works.

I know its only small, but someone who doesn't know much about programming it would probably confuse after using it the correct way in Kotlin playground. Hope you don't mind me pointing it out.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@TechSlugz 
Thank you for reaching out to us. The issue is fixed and will be published soon:
when (variable) {
    matches-value -> execute-this-code
    matches-value -> execute-this-code
    …
}
