### ISSUE TITLE
Android Basics: create-dice-roller-app-with-button

### ISSUE THREAD

**Issue by ladylazy9x** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#42]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

Hi, I'm learning on this, and it automatically sign me out, so I cannot sync progress and receive Badge to my profile.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by Yuskovich** [comment]
I have similar problem - progress regularly is not appear - pathway, activities, badges. In my case help reload (F5) web page - progress appear again.

**Comment by ladylazy9x** [comment]
> I have similar problem - progress regularly is not appearing - pathway, activities, badges. In my case help reload (F5) web page - progress appears again.

Hi, I have reported this to Google dev platform report, they seem working on it.

**Comment by osuleymanova** [comment]
@ladylazy9x 
The issue that you presented to us is extremely important, and I thank you for bringing it to our attention. Actions has been taken to fix it. Could you verify please if the issue still exists on your side. If yes, please reopen the issue.
