### ISSUE TITLE
Android Basics: conditional-dice-roll-behavior

### ISSUE THREAD

**Issue by Yuskovich** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#43]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-conditional-dice-roll-behavior?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-conditional-dice-roll-behavior#5

**In which task and step of the codelab can this issue be found?**
Add conditional behavior in Kotlin.
 6.Summary
   see screenshot - formatting problem

**Describe the problem**
mistake of formatting

**Steps to reproduce?**
1. Go to...  "Add conditional behavior in Kotlin."  -->  6.Summary
2. Click on...   scroll to end page
3. See error...  yes

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![screenshot](https://user-images.githubusercontent.com/43804573/129365707-980b2b00-86f3-4e76-aa4a-1c0f0fd248f2.jpg)

**Comment by osuleymanova** [comment]
@Yuskovich 
Thank you for reaching out to us. The issue is fixed and will be published soon:
when (variable) {
    matches-value -> execute-this-code
    matches-value -> execute-this-code
    …
}
