### ISSUE TITLE
Android Basics: conditional-dice-roll-behavior

### ISSUE THREAD

**Issue by andreysoft** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#44]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-conditional-dice-roll-behavior

**In which task and step of the codelab can this issue be found?**
step 6 Summary

**Describe the problem**
HTML encoding error in the last sample:
"`matches-value -&gt;` *`execute-this-code`*"
must be:
matches-value -> execute-this-code

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@andreysoft 
Thank you for reaching out to us. The issue is fixed and will be published soon:
when (variable) {
    matches-value -> execute-this-code
    matches-value -> execute-this-code
    …
}
