### ISSUE TITLE
Android Basics: conditional-dice-roll-behavior

### ISSUE THREAD

**Issue by SaidkamolKhan** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#46]
https://developer.android.com/codelabs/basic-android-kotlin-training-conditional-dice-roll-behavior?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-conditional-dice-roll-behavior#3

Task 4 last step

6 -> println("Apologies! you rolled a 6. Try again!")
After ending the sentence with ! you should start with a capital letter. It is a small mistake so please fix it.

**Comment by osuleymanova** [comment]
@SaidkamolKhan 
Thank you for reaching out to us. The issue is fixed and will be published soon.
