### ISSUE TITLE
Android Basics: create-dice-roller-app-with-button

### ISSUE THREAD

**Issue by mic-71** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#47]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-create-dice-roller-app-with-button?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-create-dice-roller-app-with-button#3

**In which task and step of the codelab can this issue be found?**
Enable auto imports

**Describe the problem**
The second screenshot (https://developer.android.com/codelabs/basic-android-kotlin-training-create-dice-roller-app-with-button/img/f8ce3f7a514126b.png) is wrong.
The arrow points to wrong options for the java section (Classes and Static methods and fields instead Add unambiquous imports on the fly and optimize imports on the fly). 

**Steps to reproduce?**
1. open website 
2. scroll to bottom
3. inspect last screenshot

**Versions**
- not relevant

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/89272796/130277552-3783b7c3-73f9-41f7-aac1-afe41491d920.png)

**Comment by osuleymanova** [comment]
@mic-71 
The issue that you presented to us is important, and I thank you for bringing it to our attention. Actions will soon be taken to fix it.
