### ISSUE TITLE
Android Basics: create-dice-roller-app-with-button

### ISSUE THREAD

**Issue by rizal-ashari10** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#48]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**
In the step 5 "Make Button Interactive"

**Describe the problem**
When I run the project there is a notification in 'Event log' 
Session 'app': Installation did not succeed.
		The application could not be installed: SHELL_UNRESPONSIVE
		Retry

**Versions**
_Android Studio version:_11 
_API version of the emulator:_ 30
![Trouble Shooting](https://user-images.githubusercontent.com/89144652/130337961-1ceeb1e2-bca2-4d3c-a20e-71b520575f21.jpg)

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@rizal-ashari10 
Thank you for reaching out to us. 
Since there's an error that says "The device timed out while trying to install the application", please try closing the emulator and restarting it to see if that helps. If not, feel free to reopen the issue. 
Happy coding!
