### ISSUE TITLE
Android Basics: conditional-dice-roll-behavior 

### ISSUE THREAD

**Issue by mbifulco** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#49]
**URL of codelab**
[link](https://developer.android.com/codelabs/basic-android-kotlin-training-conditional-dice-roll-behavior?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-conditional-dice-roll-behavior#5)

**In which task and step of the codelab can this issue be found?**
Step `6 - Summary`

**Describe the problem**
The illustrative description of a `when` statement is rendering incorrectly:

![image](https://user-images.githubusercontent.com/1844496/132137378-897ae20a-29ba-46f9-a439-90d8266cfb70.png)

**Steps to reproduce?**
1. Visit above UR
2. scroll to bottom of page where `when` is showcased
3. see the following rendered incorrectly:
    ```
        `matches-value -&gt;` *`execute-this-code`*
    ```

**Versions**
n/a

**Additional information**
expected fix: Should probably see something like **`matches value`** -> **`execute this code`**

**Comment by osuleymanova** [comment]
@mbifulco 
Thank you for reaching out to us. The issue is fixed and will be published soon:
when (variable) {
    matches-value -> execute-this-code
    matches-value -> execute-this-code
    …
}
