### ISSUE TITLE
Android Basics: create-dice-roller-app-with-button

### ISSUE THREAD

**Issue by brucemch** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#5]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-create-dice-roller-app-with-button?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-create-dice-roller-app-with-button#3

**In which task and step of the codelab can this issue be found?**
Introduction to Activities > Enable auto imports, step 1.

**Describe the problem**
Step 1. The described method to display the "Preferences for New Projects" dialog reflects the OSX version of Android Studio (**File > New Project Settings > Preferences for New Projects**)   
For the Windows version the method is different: **File > Other Settings > Settings for New Projects...**
This displays the "Setting for New Projects" dialog.

**Steps to reproduce?**
Described above (use Windows version).

**Versions**
_Android Studio version:_ 4.0.2 (Windows)
_API version of the emulator:_ N/A

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@brucemch 
Thank you so much for reporting this issue. This is fixed and will be published soon.
Updated the instructions but, we can't add multiple screenshots for different OS. The content inside the popup is same.
