### ISSUE TITLE
Android Basics: create-dice-roller-app-with-button

### ISSUE THREAD

**Issue by bright943nw** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#56]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-create-dice-roller-app-with-button?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-create-dice-roller-app-with-button#2

**In which task and step of the codelab can this issue be found?**
task 2, step 3

**Describe the problem**
This text shoulbe like simple text, not a code:
"Note that because this text is only viewed by app developers, you don't need to make a string resource for it."

![screenshot_0001](https://user-images.githubusercontent.com/56880306/137109248-55bf8deb-735c-4a8e-ba11-07c5bfea357f.jpg)

**Comment by osuleymanova** [comment]
@bright943nw 
Thank you for reaching out to us. The issue is fixed and will be published soon.

**Comment by bright943nw** [comment]
Thanks a lot!

вт, 30 нояб. 2021 г. в 02:55, osuleymanova ***@***.***>:
