### ISSUE TITLE
Android Basics: create-dice-roller-app-with-button

### ISSUE THREAD

**Issue by regardliss** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#6]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-create-dice-roller-app-with-button?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-create-dice-roller-app-with-button#3

**In which task and step of the codelab can this issue be found?**

Enable auto imports, Step 1.

**Describe the problem**
The instructions to enable imports for Windows is incorrect.  I am using Windows and found the information by using the instructions listed for MacOS

**Steps to reproduce?**
Instructions for Windows in Codelab: In Windows go to File > Other Setting > Setting for New Projects..
1. Go to File and look for Other Settings - it's not there :-)  If you click on Settings and then Other Settings, also not there.

**Versions**
_Android Studio version:_ 4.1.1
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@regardliss 
Thank you for reaching out to us.
Could you give the details of your Operation system? Windows or macOS?

**Comment by regardliss** [comment]
Hi,

I'm using Windows 10 Home

Thanks

**Comment by osuleymanova** [comment]
@regardliss 
Thank you for reaching out to us. The issue is fixed and published. The correct path is File > Settings > Editor > General > Auto Import.
