### ISSUE TITLE
Android Basics: create-dice-roller-in-kotlin

### ISSUE THREAD

**Issue by GPRSBirkbeck** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#62]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-create-dice-roller-in-kotlin?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-create-dice-roller-in-kotlin#5 

**In which task and step of the codelab can this issue be found?**
Task 6, stage 9

**Describe the problem**
Double spacing in the following sentence after the word "rolled"
println("Your ${mySecondDice.numSides} sided dice rolled  ${mySecondDice.roll()}!")

**Steps to reproduce?**
1. Go to... the URL
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@GPRSBirkbeck 
Thank you for reaching out to us. The issue is fixed and will be published soon.
