### ISSUE TITLE
Android Basics: conditional-dice-roll-behavior

### ISSUE THREAD

**Issue by RudolfStarosta** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#66]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-conditional-dice-roll-behavior?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-conditional-dice-roll-behavior#5

**In which task and step of the codelab can this issue be found?**
6. Summary

**Describe the problem**
The description of the when-statement shows

`matches-value -&gt;` *`execute-this-code`*

instead of  

`matches-value` -> *`execute-this-code`*

**Steps to reproduce?**
1. Go to URL
2. Click through steps until step 6
3. See error at the bottom

**Versions**
_Android Studio version:_ na
_API version of the emulator:_na 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![grafik](https://user-images.githubusercontent.com/19998957/141259217-8e5f5638-2076-44dc-9d3e-ccd465e8e6e0.png)

**Comment by RudolfStarosta** [comment]
Thanks a lot for providing the learning platform :)

**Comment by osuleymanova** [comment]
@RudolfStarosta 
Thank you for reaching out to us. The issue is fixed and will be published soon:
when (variable) {
    matches-value -> execute-this-code
    matches-value -> execute-this-code
    …
}
We appreciate your feedback as well!
