### ISSUE TITLE
Android Basics: create-dice-roller-app-with-button -DAC rendering issue 

### ISSUE THREAD

**Issue by akreitz** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#7]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-create-dice-roller-app-with-button?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-create-dice-roller-app-with-button#3

**In which task and step of the codelab can this issue be found?**
Codelab: Creating an interactive Dice Roller app
Task: Introduction to Activities
Step: 4

**Describe the problem**
Missing line between the end of step 3 and the beginning of step 4

**Steps to reproduce?**
N/A

1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/19675591/105085486-ab20cd00-5a4c-11eb-8029-969c2a71fcd0.png)

**Comment by osuleymanova** [comment]
@akreitz 
Thank you for reaching out to us. The issue is fixed and published.
