### ISSUE TITLE
Android Basics: create-dice-roller-app-with-button

### ISSUE THREAD

**Issue by TheCodingLegend** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#74]
https://developer.android.com/codelabs/basic-android-kotlin-training-create-dice-roller-app-with-button?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-create-dice-roller-app-with-button#2

Last word of the third sentence is Below the picture. It should be above the picture.
![Screenshot (42)](https://user-images.githubusercontent.com/84800257/143685435-37f7b46f-ea64-410d-9440-08901a4a52a8.png)

**Comment by osuleymanova** [comment]
@TheCodingLegend 
Thank you for reaching out to us. The issue is fixed and will be published soon.
