### ISSUE TITLE
Android Basics: create-dice-roller-in-kotlin

### ISSUE THREAD

**Issue by KSBYRD** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#75]
**URL of codelab**

**In which task and step of the codelab can this issue be found?** All through the whole codelab.

**Describe the problem**

Singular form of dice is die. All this text refers to rolling 1 die but uses the plural form.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@KSBYRD 
Thank you for your feedback. While it is true that the singular form of dice is "die", we decided that "dice" would have a more positive tone in the codelab compared to the word "die". And in some instances, people do casually use the word "dice" for singular form. Thank you again for the feedback and for taking our codelab. Hope it was a helpful learning experience!
