### ISSUE TITLE
Android Basics: conditional-dice-roll-behavior

### ISSUE THREAD

**Issue by mulv93** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#77]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-conditional-dice-roll-behavior?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-conditional-dice-roll-behavior#1
**In which task and step of the codelab can this issue be found?**
Task number 2 (end of the task - Control Flow)

**Describe the problem**
The very last instruction is: **"Use an else + if combination to add alternative conditions."**
However, when I run my code, I get the following error: "Unresolved reference: +"

fun main() {
   val num = 6
   if (num > 4) {
       println("The variable is greater than 4")
    } else if (num==4) {
     	println("The variable is equal to 4")
   } else+if (num==6) { 
       println("You're our lucky winner!!!")
   } else {
       println("The variable is less than 4")
       }
}

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@mulv93 
Thank you for reaching out to us. 
Please try to replace the line in your code 
} else+if (num==6) {
with
} else if (num == 6) {
If it doesn't help please feel free to reopen the issue.
