### ISSUE TITLE
Android Basics: conditional-dice-roll-behavior

### ISSUE THREAD

**Issue by mulv93** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#78]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-conditional-dice-roll-behavior?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-conditional-dice-roll-behavior#2

**In which task and step of the codelab can this issue be found?**
3 - Create the Lucky Dice roll game (Step 5)

**Describe the problem**
I was getting an error code when running my code, so I tried to copy-paste the code in the exercise, and received the same error message: 

**Assignments are not expressions, and only expressions are allowed in this context
Val cannot be reassigned
Type mismatch: inferred type is () -> Unit but Random was expected
Missing '}**

This was the code I copy pasted: 

fun main() {
    val myFirstDice = Dice(6)
    val rollResult = myFirstDice.roll()
    val luckyNumber=4
    if(rollResult=luckyNumber) {
        println("You win!!")
    }
}

class Dice (val numSides: Int) {
    fun roll(): Int {
        return (1..numSides).random() {
    }
}

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@mulv93 
Thank you for reaching out to us. 
Please try to replace your code
 if(rollResult=luckyNumber) { 
 with  if (rollResult == luckyNumber) {
 If ti doesn't help feel free to reopen the issue.
