### ISSUE TITLE
Android Basics: conditional-dice-roll-behavior

### ISSUE THREAD

**Issue by csvwolf** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#83]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-conditional-dice-roll-behavior?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-conditional-dice-roll-behavior#5

**In which task and step of the codelab can this issue be found?**
![image](https://user-images.githubusercontent.com/8280645/145660582-6ad592a7-3cdc-4bf9-a6a6-c5c1beb458af.png)

**Describe the problem**
The conclusion of `when` code `->` is showed by html entity.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@csvwolf 
Thank you for reaching out to us. The issue in the code snippet is fixed and will be published soon.
![Screen Shot 2022-04-08 at 4 03 42 PM](https://user-images.githubusercontent.com/86437155/162544780-8e0c30fb-3025-41b3-bf53-8a3925367273.png)
