### ISSUE TITLE
Android Basics: create-dice-roller-in-kotlin

### ISSUE THREAD

**Issue by VeloSteve** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#85]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-create-dice-roller-in-kotlin

**In which task and step of the codelab can this issue be found?**
"Before you begin"

**Describe the problem**
"Dice" is plural.  The singular is "die".  You should use "die" when referring to one cube.  To quote grammarist.com:

> The singular of dice—a plural noun referring to the small cubes used in games of chance—is die. Because the irregular plural is more common than the singular, many writers forget to use the singular at all

**Steps to reproduce?**
Read the page.

**Versions**
n/a

**Comment by karlgg** [comment]
This, a thousand times this. Would you leave this sort of glaring (but common) mistake if someone wrote "verticee" instead of "vertex"?
