### ISSUE TITLE
Android Basics: conditional-dice-roll-behavior

### ISSUE THREAD

**Issue by sibkh** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#88]
**URL of codelab**
[
](https://developer.android.com/codelabs/basic-android-kotlin-training-conditional-dice-roll-behavior?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-conditional-dice-roll-behavior#5)

**In which task and step of the codelab can this issue be found?**

Above URL
**Describe the problem**

Summary has Boolean data types but no code examples were shown/practiced throughout the codelab.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@sibkh 
Thank you for reaching out to us. Could you clarify the issue please so we might take the further actions?

**Comment by osuleymanova** [comment]
Closing this issue, since there is no issue description.
Please create a new one, if you need help.
All the best learning Android.
