### ISSUE TITLE
Android Basics: create-dice-roller-in-kotlin

### ISSUE THREAD

**Issue by ifykenchi** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#89]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**
Step 5

**Describe the problem**

The final program prints the same result for a 6 sided dice and a 20 sided dice
This also affects the code for Step 6 in a similar way

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by blackcrown01** [comment]
i finished this codlab like 3 months and reopened my file for you and i found 2 files (layout file and MainActivity ) 

i think the issue you facing is in the MainActivity with the rolling functions so i'll put down for you my solution and try tp applu it on your work 
----------------------------------
class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val rollButton: Button = findViewById(R.id.button)
        rollButton.setOnClickListener {
            rollDice()
          
        }
    private fun rollDice() {
        val dice = Dice1(6)
        val diceRoll = dice.roll()
        val resultTextView: TextView = findViewById(R.id.textView1)
        resultTextView.text = diceRoll.toString()

    }

**Comment by ifykenchi** [comment]
thanks blackcrown01
