### ISSUE TITLE
Android Basics: create-dice-roller-app-with-button

### ISSUE THREAD

**Issue by RepositorioLeonardo** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#94]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**
- Criar um app Dice Roller interativo
- Etapa 4 Introdução a atividades.

**Describe the problem**
TUTORIAL COM DIVERGÊNCIA
Na sessão "Ativar importações automáticas", é informado que para ativar o Auto Import no Android Studio devo ir em --> Other Settings --> Auto Import
Está errado, o caminho correto é File --> Settings --> General --> Auto Import

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@RepositorioLeonardo 
Obrigado por entrar em contato conosco. O caminho do local de importação automática é atualizado e será publicada em breve.
