### ISSUE TITLE
Android Basics: conditional-dice-roll-behavior

### ISSUE THREAD

**Issue by RnRJohnny** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#96]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-conditional-dice-roll-behavior?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%3Fhl%3Den%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-conditional-dice-roll-behavior&hl=en#3

**In which task and step of the codelab can this issue be found?**
Reading step 4 "A when statements starts with the keyword when..."

**Describe the problem**
Awkward. Rephrase as either "when statements start" or "A when statement starts"

**Steps to reproduce?**
1. Read it

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@RnRJohnny 
Thank you for reaching out to us. This typo is fixed and will be published soon.
