### ISSUE TITLE
Android Basics: conditional-dice-roll-behavior

### ISSUE THREAD

**Issue by Panchofromthefarm** [google-developer-training/android-basics-kotlin-create-dice-roller-with-button-app-solution#99]
**URL of codelab**
[
](https://developer.android.com/codelabs/basic-android-kotlin-training-conditional-dice-roll-behavior?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-conditional-dice-roll-behavior#2)
**In which task and step of the codelab can this issue be found?**

**Describe the problem**

so i am following the steps to create a "DICE" however every-time i enter the code on playground i keep getting the following 
"Unresolved reference: Dice"

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@Panchofromthefarm 
Thanks for reaching out to us.
We appreciate if you could provide the screenshot of your code run and the error message so we may troubleshoot.
Please refer to the screenshot provided with no error message "Unresolved reference: Dice" there:
![Screen Shot 2022-05-24 at 5 01 29 PM](https://user-images.githubusercontent.com/86437155/170151051-1f7884db-19a0-451d-a13e-180c3336c878.png)
